export const selectors = {
  loginEmail: "#login-email",
  loginPassword: "#login-password",
  loginSubmit: 'button[type="submit"]',
  sessionLoadingText: "Verifica sessione...",
  loginHeading: "Accedi al backoffice",
  appSidebar: '[data-slot="sidebar"]',
  /** Relative to Playwright baseURL (`/bazeoffice/`). No leading slash — `/path` escapes the base. */
  routes: {
    home: ".",
    pipeline: "pipeline",
    assegnazione: "assegnazione",
    ricerca: "ricerca",
  },
  pipeline: {
    heading: "Sales Pipeline",
    searchInput: '[data-testid="pipeline-search-input"]',
    applyFilters: '[data-testid="pipeline-apply-filters"]',
    resetFilters: '[data-testid="pipeline-reset-filters"]',
    column: (stageId: string) => `[data-testid="kanban-column-${stageId}"]`,
    card: (processId: string) => `[data-testid="pipeline-card-${processId}"]`,
    sheetDialog: '[role="dialog"]',
    sheetClose: '[aria-label="Chiudi dettaglio"]',
    duplicaRicerca: 'button:has-text("Duplica ricerca")',
  },
  assegnazione: {
    heading: "Assegnazione",
    unassignedPanel: '[data-testid="assegnazione-unassigned"]',
    card: (processId: string) => `[data-testid="assegnazione-card-${processId}"]`,
    dayColumn: (dateKey: string) => `[data-testid="assegnazione-day-${dateKey}"]`,
    filterRecruiter: '[data-testid="assegnazione-filter-recruiter"]',
    filterTipoRicerca: '[data-testid="assegnazione-filter-tipo-ricerca"]',
    resetFilters: '[data-testid="assegnazione-reset-filters"]',
    sheetDialog: '[role="dialog"]',
    sheetClose: '[aria-label="Chiudi"]',
  },
  ricerca: {
    heading: "Ricerche",
    searchInput: '[data-testid="ricerca-search-input"]',
    filterRecruiter: '[data-testid="ricerca-filter-recruiter"]',
    column: (stageId: string) => `[data-testid="kanban-column-${stageId}"]`,
    card: (processId: string) => `[data-testid="ricerca-card-${processId}"]`,
    backToBoard: 'button:has-text("Torna alle ricerche")',
  },
} as const
