export const selectors = {
  loginEmail: "#login-email",
  loginPassword: "#login-password",
  loginSubmit: 'button[type="submit"]',
  sessionLoadingText: "Verifica sessione...",
  loginHeading: "Accedi al backoffice",
  appSidebar: '[data-slot="sidebar"]',
  /** Relative to Playwright baseURL (`/bazeoffice/`). No leading slash — `/path` escapes the base. */
  routes: {
    home: ".",
    pipeline: "pipeline",
    assegnazione: "assegnazione",
    ricerca: "ricerca",
    cercaLavoratori: "cerca-lavoratori",
    gate1: "gate-1",
    gate2: "gate-2",
    rapportiLavorativi: "gestione-contrattuale/rapporti-lavorativi",
    assunzioni: "gestione-contrattuale/assunzioni",
  },
  pipeline: {
    heading: "Sales Pipeline",
    searchInput: '[data-testid="pipeline-search-input"]',
    applyFilters: '[data-testid="pipeline-apply-filters"]',
    resetFilters: '[data-testid="pipeline-reset-filters"]',
    column: (stageId: string) => `[data-testid="kanban-column-${stageId}"]`,
    card: (processId: string) => `[data-testid="pipeline-card-${processId}"]`,
    sheetDialog: '[role="dialog"]',
    sheetClose: '[aria-label="Chiudi dettaglio"]',
    duplicaRicerca: 'button:has-text("Duplica ricerca")',
  },
  assegnazione: {
    heading: "Assegnazione",
    unassignedPanel: '[data-testid="assegnazione-unassigned"]',
    card: (processId: string) => `[data-testid="assegnazione-card-${processId}"]`,
    dayColumn: (dateKey: string) => `[data-testid="assegnazione-day-${dateKey}"]`,
    filterRecruiter: '[data-testid="assegnazione-filter-recruiter"]',
    filterTipoRicerca: '[data-testid="assegnazione-filter-tipo-ricerca"]',
    resetFilters: '[data-testid="assegnazione-reset-filters"]',
    sheetDialog: '[role="dialog"]',
    sheetClose: '[aria-label="Chiudi"]',
  },
  ricerca: {
    heading: "Ricerche",
    searchInput: '[data-testid="ricerca-search-input"]',
    filterRecruiter: '[data-testid="ricerca-filter-recruiter"]',
    column: (stageId: string) => `[data-testid="kanban-column-${stageId}"]`,
    card: (processId: string) => `[data-testid="ricerca-card-${processId}"]`,
    backToBoard: 'button:has-text("Torna alle ricerche")',
  },
  rapporti: {
    searchInput: '[data-testid="rapporti-search-input"]',
    statusFilter: '[data-testid="rapporti-status-filter"]',
    resetFilters: '[data-testid="rapporti-reset-filtri"]',
    card: (rapportoId: string) => `[data-testid="rapporti-card-${rapportoId}"]`,
  },
  assunzioni: {
    heading: "Assunzioni",
    searchInput: '[data-testid="assunzioni-search-input"]',
    column: (stageId: string) => `[data-testid="kanban-column-${stageId}"]`,
    card: (rapportoId: string) => `[data-testid="assunzioni-card-${rapportoId}"]`,
    sheetDialog: '[role="dialog"]',
    sheetClose: '[aria-label="Chiudi"]',
  },
  lavoratori: {
    listPanel: '[data-testid="lavoratori-list-panel"]',
    searchInput: '[data-testid="lavoratori-list-panel"] input[placeholder="Cerca lavoratori..."]',
    card: (workerId: string) => `[data-testid="lavoratore-card-${workerId}"]`,
    closeDetail: '[aria-label="Chiudi scheda lavoratore"]',
    applyFilters: 'button:has-text("Applica filtri")',
    resetGateFilters: 'button:has-text("Reset filtri")',
  },
} as const
