export const selectors = {
  loginEmail: "#login-email",
  loginPassword: "#login-password",
  loginSubmit: 'button[type="submit"]',
  sessionLoadingText: "Verifica sessione...",
  loginHeading: "Accedi al backoffice",
  appSidebar: '[data-slot="sidebar"]',
  /** Relative to Playwright baseURL (`/bazeoffice/`). No leading slash — `/path` escapes the base. */
  routes: {
    home: ".",
    pipeline: "pipeline",
    assegnazione: "assegnazione",
    ricerca: "ricerca",
    cercaLavoratori: "cerca-lavoratori",
    gate1: "gate-1",
    gate2: "gate-2",
    rapportiLavorativi: "gestione-contrattuale/rapporti-lavorativi",
    assunzioni: "gestione-contrattuale/assunzioni",
    chiusure: "gestione-contrattuale/chiusure",
    variazioni: "gestione-contrattuale/variazioni",
    cedolini: "payroll/cedolini",
    contributiInps: "payroll/contributi-inps",
    ticketCustomer: "customer-support/ticket-customer",
    ticketPayroll: "customer-support/ticket-payroll",
  },
  pipeline: {
    heading: "Sales Pipeline",
    searchInput: '[data-testid="pipeline-search-input"]',
    applyFilters: '[data-testid="pipeline-apply-filters"]',
    resetFilters: '[data-testid="pipeline-reset-filters"]',
    column: (stageId: string) => `[data-testid="kanban-column-${stageId}"]`,
    card: (processId: string) => `[data-testid="pipeline-card-${processId}"]`,
    sheetDialog: '[role="dialog"]',
    sheetClose: '[aria-label="Chiudi dettaglio"]',
    duplicaRicerca: 'button:has-text("Duplica ricerca")',
  },
  assegnazione: {
    heading: "Assegnazione",
    unassignedPanel: '[data-testid="assegnazione-unassigned"]',
    card: (processId: string) => `[data-testid="assegnazione-card-${processId}"]`,
    dayColumn: (dateKey: string) => `[data-testid="assegnazione-day-${dateKey}"]`,
    filterRecruiter: '[data-testid="assegnazione-filter-recruiter"]',
    filterTipoRicerca: '[data-testid="assegnazione-filter-tipo-ricerca"]',
    resetFilters: '[data-testid="assegnazione-reset-filters"]',
    sheetDialog: '[role="dialog"]',
    sheetClose: '[aria-label="Chiudi"]',
  },
  ricerca: {
    heading: "Ricerche",
    searchInput: '[data-testid="ricerca-search-input"]',
    filterRecruiter: '[data-testid="ricerca-filter-recruiter"]',
    column: (stageId: string) => `[data-testid="kanban-column-${stageId}"]`,
    card: (processId: string) => `[data-testid="ricerca-card-${processId}"]`,
    backToBoard: 'button:has-text("Torna alle ricerche")',
  },
  rapporti: {
    searchInput: '[data-testid="rapporti-search-input"]',
    statusFilter: '[data-testid="rapporti-status-filter"]',
    resetFilters: '[data-testid="rapporti-reset-filtri"]',
    card: (rapportoId: string) => `[data-testid="rapporti-card-${rapportoId}"]`,
  },
  assunzioni: {
    heading: "Assunzioni",
    searchInput: '[data-testid="assunzioni-search-input"]',
    column: (stageId: string) => `[data-testid="kanban-column-${stageId}"]`,
    card: (rapportoId: string) => `[data-testid="assunzioni-card-${rapportoId}"]`,
    sheetDialog: '[role="dialog"]',
    sheetClose: '[aria-label="Chiudi"]',
  },
  chiusure: {
    heading: "Chiusure",
    searchInput: '[data-testid="chiusure-search-input"]',
    openAnnullamento: '[data-testid="chiusure-open-annullamento"]',
    annullamentoDialog: '[data-testid="chiusure-annullamento-dialog"]',
    column: (stageId: string) => `[data-testid="kanban-column-${stageId}"]`,
    card: (chiusuraId: string) => `[data-testid="chiusure-card-${chiusuraId}"]`,
    sheetDialog: '[role="dialog"]',
    sheetClose: '[aria-label="Chiudi"]',
  },
  variazioni: {
    heading: "Variazioni",
    searchInput: '[data-testid="variazioni-search-input"]',
    openCreate: '[data-testid="variazioni-open-create"]',
    createDialog: '[data-testid="variazioni-create-dialog"]',
    column: (stageId: string) => `[data-testid="kanban-column-${stageId}"]`,
    card: (variazioneId: string) => `[data-testid="variazioni-card-${variazioneId}"]`,
    sheetDialog: '[role="dialog"]',
    sheetClose: '[aria-label="Chiudi"]',
  },
  cedolini: {
    heading: "Cedolini",
    searchInput: '[data-testid="cedolini-search-input"]',
    column: (stageId: string) => `[data-testid="kanban-column-${stageId}"]`,
    card: (cedolinoId: string) => `[data-testid="cedolini-card-${cedolinoId}"]`,
    sheetDialog: '[data-testid="cedolini-sheet-dialog"]',
  },
  contributiInps: {
    heading: "Contributi INPS",
    searchInput: '[data-testid="contributi-inps-search-input"]',
    stageFilter: '[data-testid="contributi-inps-stage-filter"]',
    column: (stageId: string) => `[data-testid="kanban-column-${stageId}"]`,
    card: (contributoId: string) => `[data-testid="contributi-inps-card-${contributoId}"]`,
    sheetDialog: '[data-testid="contributi-inps-sheet-dialog"]',
  },
  ticketCustomer: {
    heading: "Ticket customer",
    boardPrefix: "ticket-customer",
    searchInput: '[data-testid="ticket-customer-search-input"]',
    stageFilter: '[data-testid="ticket-customer-stage-filter"]',
    openCreate: '[data-testid="ticket-customer-open-create"]',
    createDialog: '[data-testid="ticket-customer-create-dialog"]',
    sheetDialog: '[data-testid="ticket-customer-sheet-dialog"]',
    column: (stageId: string) => `[data-testid="kanban-column-${stageId}"]`,
    card: (ticketId: string) => `[data-testid="ticket-customer-card-${ticketId}"]`,
  },
  ticketPayroll: {
    heading: "Ticket payroll",
    boardPrefix: "ticket-payroll",
    searchInput: '[data-testid="ticket-payroll-search-input"]',
    stageFilter: '[data-testid="ticket-payroll-stage-filter"]',
    openCreate: '[data-testid="ticket-payroll-open-create"]',
    createDialog: '[data-testid="ticket-payroll-create-dialog"]',
    sheetDialog: '[data-testid="ticket-payroll-sheet-dialog"]',
    column: (stageId: string) => `[data-testid="kanban-column-${stageId}"]`,
    card: (ticketId: string) => `[data-testid="ticket-payroll-card-${ticketId}"]`,
  },
  lavoratori: {
    listPanel: '[data-testid="lavoratori-list-panel"]',
    searchInput: '[data-testid="lavoratori-list-panel"] input[placeholder="Cerca lavoratori..."]',
    card: (workerId: string) => `[data-testid="lavoratore-card-${workerId}"]`,
    closeDetail: '[aria-label="Chiudi scheda lavoratore"]',
    applyFilters: 'button:has-text("Applica filtri")',
    resetGateFilters: 'button:has-text("Reset filtri")',
  },
} as const
