import * as React from "react";

import { useCurrentOperatorName } from "@/hooks/use-current-operator-name";
import {
  GATE1_IN_PERSON_BOOKING_LINKS,
  includesBabysitterType,
} from "../lib/gate1-utils";
import { resolveGateViewProps } from "../lib/gate1-view-props";
import type { GateViewProps } from "../types/gate1-view";
import { useGate1ListFilters } from "./use-gate1-list-panel";
import { useGate1StatusRetain } from "./use-gate1-status-retain";
import { useGateDraft } from "./use-gate-draft";
import { useGateFieldsForm } from "./use-gate-fields-form";
import { useGateStepLayout } from "./use-gate-step-layout";
import { useLavoratoriData } from "./use-lavoratori-data";
import { useSelectedWorkerEditor } from "./use-selected-worker-editor";

export function useGate1View(props: GateViewProps) {
  const {
    gateLabel,
    workerStatus,
    workerCountLabel,
    listControlsSlot,
    showFollowup,
    showSelfCertification,
    showReferencesInWorkTypes,
    showAdministrativeFields,
    showStepper,
    splitBazeChecksStep,
    stepInfoBySection,
    presentationEditMode,
    photoEditMode,
    addressEditMode,
    workTypesEditMode,
    availabilityEditMode,
    bazeChecksEditMode,
    documentSectionMode,
    showAssessment,
    specificChecksMode,
    specificChecksEditMode,
    applyGate1BaseFilters,
    showCertificationReferente,
    showFollowupFilter,
    allowCertifiedStatus,
    showInPersonBookingLinks,
    stepLayout,
  } = resolveGateViewProps(props);

  const {
    gateProvinciaFilter,
    setGateProvinciaFilter,
    gateFollowupFilter,
    setGateFollowupFilter,
  } = useGate1ListFilters();
  const {
    workers,
    workerRows,
    workerAddressesById,
    selectedWorkerId,
    setSelectedWorkerId,
    selectedWorker,
    selectedWorkerRow,
    selectedWorkerAddress,
    selectedWorkerDocuments,
    loadingSelectedWorkerDocuments,
    selectedWorkerExperiences,
    loadingSelectedWorkerExperiences,
    selectedWorkerReferences,
    loadingSelectedWorkerReferences,
    loading,
    error,
    setError,
    lookupOptionsByDomain,
    lookupColorsByDomain,
    filterFields,
    loadWorkersSchema,
    table,
    searchValue,
    setSearchValue,
    filters,
    setFilters,
    hasPendingFilters,
    applyFilters,
    savedViews,
    activeViewId,
    saveCurrentView,
    applySavedView,
    deleteSavedView,
    setPageIndex,
    pageCount,
    currentPage,
    applyUpdatedWorkerRow,
    applyUpdatedWorkerAddress,
    applyUpdatedWorkerExperience,
    appendCreatedWorkerExperience,
    removeWorkerExperience,
    applyUpdatedWorkerReference,
    appendCreatedWorkerReference,
    upsertSelectedWorkerDocument,
  } = useLavoratoriData({
    forcedWorkerStatus: workerStatus,
    applyGate1BaseFilters,
    includeRelatedSelectionDetails: false,
    gate1ProvinciaFilter: gateProvinciaFilter,
    gate1FollowupFilter: gateFollowupFilter,
  });
  const groupingOptions = React.useMemo(
    () =>
      filterFields.map((field) => ({ label: field.label, value: field.value })),
    [filterFields],
  );

  const gate1Editor = useSelectedWorkerEditor({
    selectedWorkerId,
    selectedWorker,
    selectedWorkerRow,
    selectedWorkerAddress,
    lookupColorsByDomain,
    setError,
    applyUpdatedWorkerRow,
    applyUpdatedWorkerAddress,
    applyUpdatedWorkerExperience,
    appendCreatedWorkerExperience,
    removeWorkerExperience,
    applyUpdatedWorkerReference,
    appendCreatedWorkerReference,
  });

  const {
    selectedWorkerIsNonIdoneo,
    selectedWorkerNonQualificatoIssues,
    selectedWorkerIsNonQualificato,
    availabilityPayload,
    disponibilitaBadgeClassName,
    availabilityReadOnlyRows,
    nonIdoneoReasonValues,
    blacklistChecked,
    recruiterFeedbackEntries,
    isEditingHeader,
    setIsEditingHeader,
    isEditingAddress,
    setIsEditingAddress,
    isEditingExperience,
    setIsEditingExperience,
    isEditingSkills,
    setIsEditingSkills,
    isEditingDocuments,
    setIsEditingDocuments,
    selectedPresentationPhotoIndex,
    setSelectedPresentationPhotoIndex,
    addressDraft,
    setAddressDraft,
    availabilityDraft,
    setAvailabilityDraft,
    availabilityStatusDraft,
    setAvailabilityStatusDraft,
    jobSearchDraft,
    setJobSearchDraft,
    experienceDraft,
    skillsDraft,
    setSkillsDraft,
    documentsDraft,
    setDocumentsDraft,
    resolvedIban,
    presentationPhotoSlots,
    updatingAvailability,
    updatingAvailabilityStatus,
    updatingExperience,
    updatingSkills,
    updatingDocuments,
    updatingNonIdoneo,
    updatingNonQualificato,
    handleNonIdoneoReasonsChange,
    patchSelectedWorkerField,
    patchWorkerAddressField,
    commitAddressField,
    saveWorkerAvailability,
    patchWorkerAvailabilityStatus,
    handleAvailabilityMatrixChange,
    patchExperienceRecord,
    createExperienceRecord,
    patchReferenceRecord,
    createReferenceRecord,
    patchSkillsField,
    patchDocumentField,
    generateStripeAccount,
    AVAILABILITY_EDIT_DAYS,
    AVAILABILITY_EDIT_BANDS,
    AVAILABILITY_HOUR_LABELS,
  } = gate1Editor;

  const operatorName = useCurrentOperatorName();
  const { gateDraft, setGateDraft } = useGateDraft({
    selectedWorkerId,
    selectedWorkerRow,
  });
  const gateFields = useGateFieldsForm({
    selectedWorkerRow,
    selectedWorkerAddress,
    lookupOptionsByDomain,
    resolvedIban,
    setGateDraft,
    setAvailabilityDraft,
    setAddressDraft,
    setJobSearchDraft,
    setSkillsDraft,
    setAvailabilityStatusDraft,
    setDocumentsDraft,
    patchSelectedWorkerField,
    patchSkillsField,
    patchWorkerAvailabilityStatus,
    patchDocumentField,
    commitAddressField,
    patchWorkerAddressField,
  });
  const {
    retainSelectedWorkerAfterStatusChange,
    statusChangeRetainedWorkerId,
  } = useGate1StatusRetain();
  const stepLayoutState = useGateStepLayout({
    documentSectionMode,
    showSelfCertification,
    stepLayout,
    showCertificationReferente,
    showFollowup,
    showAssessment,
    splitBazeChecksStep,
    presentationEditMode,
    addressEditMode,
    workTypesEditMode,
    availabilityEditMode,
    bazeChecksEditMode,
    specificChecksEditMode,
    selectedWorkerId,
    isEditingHeader,
    isEditingAddress,
    isEditingExperience,
    isEditingSkills,
    isEditingDocuments,
  });

  return {
    GATE1_IN_PERSON_BOOKING_LINKS,
    includesBabysitterType,
    activeViewId,
    addressEditMode,
    allowCertifiedStatus,
    applyFilters,
    applySavedView,
    applyUpdatedWorkerRow,
    availabilityDraft,
    availabilityEditMode,
    availabilityPayload,
    availabilityReadOnlyRows,
    availabilityStatusDraft,
    AVAILABILITY_EDIT_BANDS,
    AVAILABILITY_EDIT_DAYS,
    AVAILABILITY_HOUR_LABELS,
    addressDraft,
    bazeChecksEditMode,
    blacklistChecked,
    commitAddressField,
    createExperienceRecord,
    createReferenceRecord,
    currentPage,
    deleteSavedView,
    disponibilitaBadgeClassName,
    documentsDraft,
    error,
    experienceDraft,
    filterFields,
    filters,
    gate1Editor,
    gateDraft,
    gateFollowupFilter,
    gateLabel,
    gateProvinciaFilter,
    generateStripeAccount,
    groupingOptions,
    handleAvailabilityMatrixChange,
    handleNonIdoneoReasonsChange,
    hasPendingFilters,
    isEditingAddress,
    isEditingDocuments,
    isEditingExperience,
    isEditingHeader,
    isEditingSkills,
    jobSearchDraft,
    listControlsSlot,
    loading,
    loadingSelectedWorkerDocuments,
    loadingSelectedWorkerExperiences,
    loadingSelectedWorkerReferences,
    loadWorkersSchema,
    lookupColorsByDomain,
    lookupOptionsByDomain,
    nonIdoneoReasonValues,
    operatorName,
    pageCount,
    patchDocumentField,
    patchExperienceRecord,
    patchReferenceRecord,
    patchSelectedWorkerField,
    patchSkillsField,
    patchWorkerAddressField,
    patchWorkerAvailabilityStatus,
    photoEditMode,
    presentationEditMode,
    presentationPhotoSlots,
    recruiterFeedbackEntries,
    resolvedIban,
    retainSelectedWorkerAfterStatusChange,
    saveCurrentView,
    saveWorkerAvailability,
    savedViews,
    searchValue,
    selectedWorkerIsNonIdoneo,
    selectedWorkerIsNonQualificato,
    selectedWorkerNonQualificatoIssues,
    setError,
    selectedPresentationPhotoIndex,
    selectedWorker,
    selectedWorkerAddress,
    selectedWorkerDocuments,
    selectedWorkerExperiences,
    selectedWorkerId,
    selectedWorkerReferences,
    selectedWorkerRow,
    setAddressDraft,
    setAvailabilityDraft,
    setAvailabilityStatusDraft,
    setDocumentsDraft,
    setFilters,
    setGateDraft,
    setGateFollowupFilter,
    setGateProvinciaFilter,
    setIsEditingAddress,
    setIsEditingDocuments,
    setIsEditingExperience,
    setIsEditingHeader,
    setIsEditingSkills,
    setJobSearchDraft,
    setPageIndex,
    setSearchValue,
    setSelectedPresentationPhotoIndex,
    setSelectedWorkerId,
    setSkillsDraft,
    statusChangeRetainedWorkerId,
    showAdministrativeFields,
    showAssessment,
    showCertificationReferente,
    showFollowup,
    showFollowupFilter,
    showInPersonBookingLinks,
    showReferencesInWorkTypes,
    showStepper,
    skillsDraft,
    specificChecksEditMode,
    specificChecksMode,
    splitBazeChecksStep,
    stepInfoBySection,
    table,
    updatingAvailability,
    updatingAvailabilityStatus,
    updatingDocuments,
    updatingExperience,
    updatingNonIdoneo,
    updatingNonQualificato,
    updatingSkills,
    upsertSelectedWorkerDocument,
    workTypesEditMode,
    workerAddressesById,
    workerCountLabel,
    workerRows,
    workerStatus,
    workers,
    ...gateFields,
    ...stepLayoutState,
  };
}
