type JsonObject = Record<string, unknown>

export type LavoratoreRecord = {
  id: string
  active_selection_json: string | null
  anni_esperienza_babysitter: number | null
  anni_esperienza_badante: number | null
  anni_esperienza_colf: number | null
  availability_final_json: string | null
  bio_personale: string | null
  cap: string | null
  check_accetta_babysitting_multipli_bambini: string | null
  check_accetta_babysitting_neonati: string | null
  check_accetta_case_con_cani: string | null
  check_accetta_case_con_cani_grandi: string | null
  check_accetta_case_con_gatti: string | null
  check_accetta_funzionamento_baze: string | null
  check_accetta_lavori_con_trasferta: string | null
  check_accetta_multipli_contratti: string | null
  check_accetta_paga_9_euro_netti: string | null
  check_accetta_salire_scale_o_soffitti_alti: string | null
  check_blacklist: string | null
  check_conferma_certificazione_inviata: boolean | null
  check_conferma_idoneita_inviata: boolean | null
  check_lavori_accettabili: string[] | null
  cognome: string | null
  come_hai_conosciuto_baze: string | null
  come_ti_sposti: string[] | null
  compatibilita_babysitting_neonati: string | null
  compatibilita_con_animali_in_casa: string | null
  compatibilita_con_case_di_grandi_dimensioni: string | null
  compatibilita_con_contesti_pacati: string | null
  compatibilita_con_cucina_strutturata: string | null
  compatibilita_con_elevata_autonomia_richiesta: string | null
  compatibilita_con_stiro_esigente: string | null
  compatibilita_famiglie_molto_esigenti: string | null
  compatibilita_famiglie_numerose: string | null
  compatibilita_lavoro_con_datore_presente_in_casa: string | null
  conoscenza_dellitaliano: string | null
  consenso_newsletter: boolean | null
  cosa_so_fare: string[] | null
  creato_da_candidatura: boolean | null
  cv: JsonObject | null
  data_di_nascita: string | null
  data_ritorno_disponibilita: string | null
  data_scadenza_naspi: string | null
  data_ultima_candidatura: string | null
  descrizione: string | null
  descrizione_pubblica: string | null
  descrizione_rivista: string | null
  disponibilita: string | null
  disponibilita_domenica_mattina: boolean | null
  disponibilita_domenica_notte: boolean | null
  disponibilita_domenica_pomeriggio: boolean | null
  disponibilita_domenica_sera: boolean | null
  disponibilita_giovedi_mattina: boolean | null
  disponibilita_giovedi_notte: boolean | null
  disponibilita_giovedi_pomeriggio: boolean | null
  disponibilita_giovedi_sera: boolean | null
  disponibilita_lunedi_mattina: boolean | null
  disponibilita_lunedi_notte: boolean | null
  disponibilita_lunedi_pomeriggio: boolean | null
  disponibilita_lunedi_sera: boolean | null
  disponibilita_martedi_mattina: boolean | null
  disponibilita_martedi_notte: boolean | null
  disponibilita_martedi_pomeriggio: boolean | null
  disponibilita_martedi_sera: boolean | null
  disponibilita_mercoledi_mattina: boolean | null
  disponibilita_mercoledi_notte: boolean | null
  disponibilita_mercoledi_pomeriggio: boolean | null
  disponibilita_mercoledi_sera: boolean | null
  disponibilita_nel_giorno: string[] | null
  disponibilita_sabato_mattina: boolean | null
  disponibilita_sabato_notte: boolean | null
  disponibilita_sabato_pomeriggio: boolean | null
  disponibilita_sabato_sera: boolean | null
  disponibilita_venerdi_mattina: boolean | null
  disponibilita_venerdi_notte: boolean | null
  disponibilita_venerdi_pomeriggio: boolean | null
  disponibilita_venerdi_sera: boolean | null
  docs_scadenza_permesso_di_soggiorno: string | null
  documenti_in_regola: string | null
  email: string | null
  fbclid: string | null
  feedback_recruiter: string | null
  followup_chiamata_idoneita: string | null
  foto: JsonObject | null
  gclid: string | null
  hai_referenze: string | null
  iban: string | null
  id_stripe_account: string | null
  indirizzo_residenza_completo: string | null
  referente_idoneita_id: string | null
  referente_certificazione_id: string | null
  livello_babysitting: string | null
  livello_cucina: string | null
  livello_dogsitting: string | null
  livello_giardinaggio: string | null
  livello_inglese: string | null
  livello_italiano: string | null
  livello_pulizie: string | null
  livello_stiro: string | null
  motivazione_non_idoneo: string[] | null
  nazionalita: string | null
  nome: string | null
  paga_oraria_richiesta: number | null
  permalink_foto: string | null
  provincia: string | null
  /**
   * Non è una colonna di `public.lavoratori`: arriva dalla RPC `gate1_lavoratori`
   * che la espone facendo lateral join su `indirizzi.provincia_sigla`. Sempre
   * `undefined` per query dirette su `lavoratori` (es. path Gate 2 / Cerca).
   */
  provincia_sigla?: string | null
  rating_atteggiamento: number | null
  rating_capacita_comunicative: number | null
  rating_corporatura: string | null
  rating_cura_personale: number | null
  rating_precisione_puntualita: number | null
  referrer_id: string | null
  riassunto_profilo_breve: string | null
  sesso: string | null
  situazione_lavorativa_attuale: string | null
  stato_lavoratore: string | null
  stato_verifica_documenti: string | null
  telefono: string | null
  tipo_lavoro_domestico: string[] | null
  tipo_rapporto_lavorativo: string[] | null
  ultima_modifica: string | null
  ultima_modifica_disponibilita: string | null
  utm_campaign: string | null
  utm_content: string | null
  utm_medium: string | null
  utm_source: string | null
  utm_term: string | null
  vincoli_orari_disponibilita: string | null
  vincoli_orari_disponibilita_json: string | null
  worker_availability_last_modified: string | null
  airtable_id: string | null
  creato_il: string | null
  aggiornato_il: string | null
  metadati_migrazione: JsonObject | null
}
