type JsonObject = Record<string, unknown>

export type ProcessoMatchingRecord = {
  id: string
  annuncio_webflow: string | null
  appunti_chiamata_sales: string | null
  appunti_generali_sul_cliente: string | null
  brainstorm_slug: string | null
  campaign_id_klaaryo: string | null
  cap_link_id: string | null
  channel_grouped: string | null
  channel_grouped_copy: string | null
  check_synced_looker_studio: boolean | null
  colloqui_fatti_okr_calcolo: number | null
  colloquio_lista_domande: string[] | null
  count_pubblicazioni: number | null
  count_pubblicazioni_in_gruppo_facebook: number | null
  criticit: string | null
  da_inviare_in_newsletter: boolean | null
  data_assegnazione: string | null
  data_chiusura: string | null
  data_limite_invio_selezione: string | null
  data_ora_di_creazione: string | null
  data_per_ricerca_futura: string | null
  data_ultima_modifica: string | null
  deadline_mobile: string | null
  descrizione_animali_in_casa: string | null
  descrizione_casa: string | null
  descrizione_lavoratore_ideale: string | null
  descrizione_richiesta_ferie: string | null
  descrizione_richiesta_giorni_riposo: string | null
  descrizione_richiesta_trasferte: string | null
  descrizione_seo_webflow: string | null
  descrizione_ultime_colf_cliente: string | null
  dettagli_o_specifiche_aggiuntive: string | null
  di_cosa_si_dovra_occupare: string[] | null
  difficolt_ricerca: number | null
  disponibilita_colloqui_in_presenza: string | null
  disponibilita_domenica_mattina: string | null
  disponibilita_domenica_notte: string | null
  disponibilita_domenica_pomeriggio: string | null
  disponibilita_domenica_sera: string | null
  disponibilita_giovedi_mattina: string | null
  disponibilita_giovedi_notte: string | null
  disponibilita_giovedi_pomeriggio: string | null
  disponibilita_giovedi_sera: string | null
  disponibilita_lunedi_mattina: string | null
  disponibilita_lunedi_notte: string | null
  disponibilita_lunedi_pomeriggio: string | null
  disponibilita_lunedi_sera: string | null
  disponibilita_martedi_mattina: string | null
  disponibilita_martedi_notte: string | null
  disponibilita_martedi_pomeriggio: string | null
  disponibilita_martedi_sera: string | null
  disponibilita_mercoledi_mattina: string | null
  disponibilita_mercoledi_notte: string | null
  disponibilita_mercoledi_pomeriggio: string | null
  disponibilita_mercoledi_sera: string | null
  disponibilita_sabato_mattina: string | null
  disponibilita_sabato_notte: string | null
  disponibilita_sabato_pomeriggio: string | null
  disponibilita_sabato_sera: string | null
  disponibilita_venerdi_mattina: string | null
  disponibilita_venerdi_notte: string | null
  disponibilita_venerdi_pomeriggio: string | null
  disponibilita_venerdi_sera: string | null
  eta_ideale: number | null
  eta_massima: number | null
  eta_minima: number | null
  famiglia_id: string | null
  family_availability_json: string | null
  fascia_eta_ideale: string[] | null
  fase_processo_res: string | null
  fbclid: string | null
  fine_raccolta_candidature: string | null
  firma_preventivo: JsonObject | null
  flessibilita_giorni: string | null
  flessibilita_orari: string | null
  frequenza_rapporto: string | null
  from_onboarding: string | null
  gclid: string | null
  geocode: string | null
  gift_card_code: number | null
  gift_card_type: string | null
  id_cronjob_follow_up_dopo_colloqui: string | null
  id_hubspot: string | null
  indirizzo_prova_cap: string | null
  indirizzo_prova_citofono: string | null
  indirizzo_prova_civico: string | null
  indirizzo_prova_comune: string | null
  indirizzo_prova_note: string | null
  indirizzo_prova_provincia: string | null
  indirizzo_prova_via: string | null
  informazioni_extra_riservate: string | null
  interesse_consulenza: string | null
  introduzione_annuncio: string | null
  is_pagante_manuale: boolean | null
  is_sent_email_presentazione_referente: boolean | null
  lavoratori_selezionati_2: string | null
  link_pagamento_stripe_annuale: string | null
  link_pagamento_stripe_mensile: string | null
  link_typeform: string | null
  liquidity: string | null
  log_sales: string | null
  luogo_id: string | null
  mansioni_richieste: string | null
  mansioni_richieste_transformed_ai: string | null
  metratura_casa: string | null
  modalita_tariffa: string | null
  modello_smartmatching: string | null
  momento_disponibilita: string[] | null
  momento_giornata: string | null
  momento_settimana: string | null
  motivazione_lost: string | null
  motivazione_oot: string | null
  motivo_no_match: string | null
  must_have_ricerca: string | null
  nice_to_have_ricerca: string | null
  nucleo_famigliare: string | null
  numero_giorni_settimanali: string | null
  numero_lavoratori_da_ricevere_smart_matching: number | null
  numero_ricerca_attivata: number | null
  offerta: string | null
  old_stato_sales: string | null
  orario_di_lavoro: string | null
  ore_settimanale: string | null
  paga_mensile: string | null
  paga_oraria: string | null
  patente: string[] | null
  pipedrive_lead_id: string | null
  pipeline: string | null
  preferenza_giorno: string[] | null
  presenza_animali_in_casa: boolean | null
  presenza_informazioni_riservate: boolean | null
  preventivo_firmato: boolean | null
  prima_scelta_pagamento_webapp: string | null
  prodotto_stripe_custom_id: string | null
  pubblicazioni_annunci: string | null
  qualificazione_lead: string | null
  rapporti_lavorativi: string | null
  recruiter_ricerca_e_selezione_id: string | null
  referente_ricerca_e_selezione_id: string | null
  richiesta_ferie: boolean | null
  richiesta_patente: boolean | null
  richiesta_trasferte: boolean | null
  sales_cold_call_followup: string | null
  sales_no_show_followup: string | null
  sesso: string | null
  slug_short_job_outreach_whatsapp: string | null
  source_question: string | null
  source_url: string | null
  src_embed_maps_annucio: string | null
  stato_messaggi_whatsapp_shortlist: string | null
  stato_res: string | null
  stato_sales: string | null
  stato_whatsapp_invito_colloquio: string | null
  stipendio_type_structured_data: string | null
  stipendio_value_hour: string | null
  stipendio_value_month: string | null
  tasks: string | null
  temp_checkbox_recupero: boolean | null
  temp_risposta_wa: boolean | null
  test_colloquio_prova: boolean | null
  test_unico_profilo: boolean | null
  testo_annuncio_webflow: string | null
  testo_annuncio_whatsapp: string | null
  tipo_incontro_famiglia_lavoratore: string | null
  tipo_lavoro: string[] | null
  tipo_rapporto: string[] | null
  titolo_annuncio: string | null
  totale_candidati_copy: number | null
  urgenza: string | null
  url_panoramica_ricerca_shorten: string | null
  url_shorten_facebook: string | null
  url_shorten_facebook_page: string | null
  url_shorten_telegram: string | null
  url_shorten_whatsapp: string | null
  url_whatsapp_shortio: string | null
  utm_campaign: string | null
  utm_content: string | null
  utm_medium: string | null
  utm_source: string | null
  utm_term: string | null
  wa_conferma_avvio_ricerca: string | null
  airtable_id: string | null
  airtable_record_id: string | null
  creato_il: string | null
  aggiornato_il: string | null
  metadati_migrazione: JsonObject | null
}
