import type { LavoratoreListItem } from "@/components/lavoratori/lavoratore-card";
import type {
  CrmPipelineCardData,
  LookupOptionsByField,
} from "@/hooks/use-crm-pipeline-preview";
import type { RicercaBoardCardData } from "@/hooks/use-ricerca-board";
import type { LavoratoreRecord } from "@/types/entities/lavoratore";

export const mockWorker: LavoratoreListItem = {
  id: "worker-story-1",
  nomeCompleto: "Noelia Alfaro",
  immagineUrl: "/worker_placeholder_1.png",
  travelTimeMinutes: 28,
  locationLabel: "Milano 20141",
  telefono: "+39 333 123 4567",
  isBlacklisted: false,
  tipoRuolo: "Colf",
  tipoRuoloColor: "blue",
  tipoLavoro: "Part time",
  tipoLavoroColor: "blue",
  ruoliDomestici: ["Colf", "Tata", "Badante"],
  eta: 48,
  anniEsperienzaColf: 6,
  anniEsperienzaBabysitter: 3,
  statoLavoratore: "Idoneo",
  statoLavoratoreColor: "green",
  disponibilita: "Disponibile",
  disponibilitaColor: "green",
  isDisponibile: true,
  isQualified: true,
  isIdoneo: true,
  isCertificato: false,
  otherActiveSelections: {
    count: 1,
    dots: [{ key: "match", colorClassName: "bg-emerald-500", label: "Match" }],
    details: [
      {
        id: "selection-story-1",
        familyName: "Famiglia Giannobi",
        ricercaLabel: "Ricerca attiva",
        recruiterLabel: "Francesca",
        statoSelezione: "Prova con cliente",
        statoSelezioneColor: "blue",
        statoRicerca: "fase di colloqui",
        statoRicercaColor: "amber",
        orarioDiLavoro: "lun-ven, 8:30-13:30",
        zona: "Milano • 20141",
        appunti: "Disponibile da subito",
      },
    ],
  },
};

export const mockWorkerRow = {
  id: mockWorker.id,
  nome: "Noelia",
  cognome: "Alfaro",
  email: "noelia.alfaro@example.com",
  telefono: mockWorker.telefono,
  sesso: "Donna",
  nazionalita: "Peru",
  data_di_nascita: "1978-04-24",
  descrizione_pubblica:
    "Persona affidabile, precisa e disponibile per lavori domestici e cura bambini.",
  foto: [{ name: "foto.png", path: "lavoratori/story/foto.png", type: "image/png" }],
  stato_lavoratore: "Idoneo",
  disponibilita: "Disponibile",
  provincia: "Milano",
  cap: "20141",
  come_ti_sposti: ["Mi sposto con i mezzi"],
  tipo_lavoro_domestico: ["Colf", "Tata"],
  tipo_rapporto_lavorativo: ["Part time"],
  check_lavori_accettabili: ["Lavori di 3 giorni", "Lavori di 5 giorni"],
  check_accetta_lavori_con_trasferta: "Accetta",
  check_accetta_multipli_contratti: "Accetta",
  check_accetta_paga_9_euro_netti: "Accetta",
} as Partial<LavoratoreRecord> as LavoratoreRecord;

export const lookupOptions = {
  province: [
    { label: "Milano", value: "Milano" },
    { label: "Roma", value: "Roma" },
  ],
  mobility: [
    { label: "Mi sposto con i mezzi", value: "mezzi" },
    { label: "Mi sposto in auto", value: "auto" },
  ],
  availability: [
    { label: "Disponibile", value: "Disponibile" },
    { label: "Non disponibile", value: "Non disponibile" },
  ],
  yesNo: [
    { label: "Accetta", value: "Accetta" },
    { label: "Non accetta", value: "Non accetta" },
  ],
  lavori: [
    { label: "Colf", value: "Colf" },
    { label: "Tata", value: "Tata" },
    { label: "Badante", value: "Badante" },
  ],
  rapporti: [
    { label: "Part time", value: "Part time" },
    { label: "Full time", value: "Full time" },
  ],
  giorni: [
    { label: "Lavori di 3 giorni", value: "Lavori di 3 giorni" },
    { label: "Lavori di 5 giorni", value: "Lavori di 5 giorni" },
  ],
};

export const lookupColorsByDomain = new Map<string, string>([
  ["lavoratori.disponibilita:Disponibile", "green"],
  ["lavoratori.stato_lavoratore:Idoneo", "green"],
  ["lavoratori.stato_verifica_documenti:Documenti verificati", "green"],
  ["lavoratori.documenti_in_regola:Ho tutti i documenti in regola", "green"],
  ["lavoratori.check_accetta_lavori_con_trasferta:Accetta", "green"],
  ["lavoratori.check_accetta_multipli_contratti:Accetta", "green"],
  ["lavoratori.check_accetta_paga_9_euro_netti:Accetta", "green"],
  ["lavoratori.tipo_lavoro_domestico:Colf", "blue"],
  ["lavoratori.tipo_lavoro_domestico:Tata", "blue"],
  ["lavoratori.tipo_lavoro_domestico:Badante", "blue"],
  ["lavoratori.tipo_rapporto_lavorativo:Part time", "blue"],
  ["lavoratori.check_lavori_accettabili:Lavori di 3 giorni", "blue"],
  ["lavoratori.check_lavori_accettabili:Lavori di 5 giorni", "blue"],
  ["selezioni_lavoratori.stato_selezione:Da colloquiare", "blue"],
  ["selezioni_lavoratori.stato_selezione:Non risponde", "amber"],
  ["selezioni_lavoratori.stato_selezione:No match", "red"],
]);

export const mockRicercaCard: RicercaBoardCardData = {
  id: "220e0afe-081f-5a76-a07c-1789386fa4f6",
  stage: "fase di colloquio",
  nomeFamiglia: "Lorenza",
  cognomeFamiglia: "Giannobi",
  email: "lorenza.giannobi@example.com",
  telefono: "+39 333 987 6543",
  operatorId: "operator-story-1",
  oreSettimanali: "20",
  giorniSettimanali: "5",
  deadline: "30/04/2026",
  deadlineRaw: "2026-04-30",
  zona: "Milano • Piano 14",
  tipoLavoroBadge: "Colf / Pulizie",
  tipoLavoroColor: "blue",
  tipoRapportoBadge: "Part time",
  tipoRapportoColor: "blue",
};

export const mockCrmLookupOptions: LookupOptionsByField = {
  stato_sales: [
    { valueKey: "warm_lead", valueLabel: "Warm - Lead", color: "red", sortOrder: 1 },
    { valueKey: "hot_ingresso", valueLabel: "Hot - Ingresso", color: "rose", sortOrder: 2 },
    {
      valueKey: "hot_contatto_avvenuto",
      valueLabel: "Hot - Contatto avvenuto",
      color: "amber",
      sortOrder: 3,
    },
    {
      valueKey: "won_ricerca_attivata",
      valueLabel: "Won - Ricerca avviata",
      color: "green",
      sortOrder: 4,
    },
    { valueKey: "lost", valueLabel: "Lost", color: "slate", sortOrder: 5 },
  ],
  stato_res: [
    { valueKey: "fare_ricerca", valueLabel: "Fare ricerca", color: "blue", sortOrder: 1 },
    { valueKey: "fase_di_colloquio", valueLabel: "Fase di colloquio", color: "amber", sortOrder: 2 },
    { valueKey: "match", valueLabel: "Match", color: "green", sortOrder: 3 },
  ],
  qualificazione_lead: [
    { valueKey: "qualificata", valueLabel: "Qualificata", color: "green", sortOrder: 1 },
    { valueKey: "da_qualificare", valueLabel: "Da qualificare", color: "amber", sortOrder: 2 },
  ],
  tipo_lavoro_domestico: [
    { valueKey: "colf_pulizie", valueLabel: "Colf / Pulizie", color: "blue", sortOrder: 1 },
    { valueKey: "badante", valueLabel: "Badante", color: "blue", sortOrder: 2 },
  ],
  tipo_rapporto_lavorativo: [
    { valueKey: "part_time", valueLabel: "Part time", color: "blue", sortOrder: 1 },
    { valueKey: "full_time", valueLabel: "Full time", color: "blue", sortOrder: 2 },
  ],
  preventivo_accettato: [
    { valueKey: "true", valueLabel: "Accettato", color: "green", sortOrder: 1 },
    { valueKey: "false", valueLabel: "Non accettato", color: "red", sortOrder: 2 },
  ],
  tipo_incontro_famiglia_lavoratore: [
    { valueKey: "in_presenza", valueLabel: "In presenza", color: "blue", sortOrder: 1 },
    { valueKey: "videochiamata", valueLabel: "Videochiamata", color: "blue", sortOrder: 2 },
  ],
  motivo_no_match: [
    { valueKey: "budget", valueLabel: "Budget", color: "red", sortOrder: 1 },
    { valueKey: "zona", valueLabel: "Zona", color: "amber", sortOrder: 2 },
  ],
  motivazione_lost: [
    { valueKey: "non_interessata", valueLabel: "Non interessata", color: "red", sortOrder: 1 },
  ],
  motivazione_oot: [
    { valueKey: "fuori_zona", valueLabel: "Fuori zona", color: "red", sortOrder: 1 },
  ],
};

export const mockCrmCard: CrmPipelineCardData = {
  id: "220e0afe-081f-5a76-a07c-1789386fa4f6",
  famigliaId: "famiglia-story-1",
  numeroRicercaAttivata: "1",
  stage: "hot_contatto_avvenuto",
  nomeFamiglia: "Famiglia Lorenza Giannobi",
  email: "lorenza.giannobi@example.com",
  telefono: "+39 333 987 6543",
  dataLead: "18/03/2026",
  tipoLavoroBadge: "Colf / Pulizie",
  tipoLavoroColor: "blue",
  tipoRapportoBadge: "Part time",
  tipoRapportoColor: "blue",
  statoRes: "fase_di_colloquio",
  qualificazioneLead: "qualificata",
  motivoNoMatch: "",
  modelloSmartmatching: "standard",
  oreSettimana: "20",
  giorniSettimana: "5",
  giornatePreferite: ["Lunedì", "Martedì", "Mercoledì", "Giovedì", "Venerdì"],
  salesColdCallFollowup: "",
  salesNoShowFollowup: "",
  motivazioneLost: "",
  motivazioneOot: "",
  appuntiChiamataSales: "Famiglia disponibile a iniziare entro due settimane.",
  dataPerRicercaFutura: "-",
  dataCallPrenotata: "23/04/2026, 10:30",
  dataLeadRaw: "2026-03-18",
  dataPerRicercaFuturaRaw: null,
  dataCallPrenotataRaw: "2026-04-23T10:30:00+00:00",
  tentativiChiamataCount: 1,
  preventivoAccettato: true,
  orarioDiLavoro: "lun-ven, 8:30-13:30",
  nucleoFamigliare: "Coppia con due bambini di 6 e 9 anni.",
  descrizioneCasa: "Appartamento su un piano, circa 110 mq.",
  metraturaCasa: "110",
  descrizioneAnimaliInCasa: "Un gatto tranquillo.",
  mansioniRichieste: "Pulizie, stiro leggero, preparazione pranzo.",
  informazioniExtraRiservate: "Preferiscono una persona autonoma e precisa.",
  etaMinima: "35",
  etaMassima: "60",
  indirizzoProvincia: "Milano",
  indirizzoCap: "20141",
  indirizzoNote: "Piano 14",
  indirizzoCompleto: "Via Roma 10, Milano",
  srcEmbedMapsAnnucio: "",
  deadlineMobile: "30/04/2026",
  disponibilitaColloquiInPresenza: "Martedì e giovedì pomeriggio",
  familyAvailabilityJson: null,
  tipoIncontroFamigliaLavoratore: "in_presenza",
  richiestaPatente: false,
  richiestaTrasferte: false,
  richiestaFerie: true,
  descrizioneRichiestaTrasferte: "",
  descrizioneRichiestaFerie: "Agosto escluso.",
  patenteDettaglio: "",
  sesso: null,
  testoAnnuncioWhatsapp:
    "Famiglia a Milano cerca colf part time lun-ven mattina. Richiesta esperienza in pulizie e stiro.",
};
